# Generated by Django 5.1.1 on 2024-09-21 10:32

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social_media.models.image_path
            ),
        ),
    ]
