# Generated by Django 5.1.1 on 2024-09-17 13:45

import django.utils.timezone
import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                null=True, upload_to=social_media.models.image_path
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="social_media.post"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social_media.models.image_path
            ),
        ),
    ]
