# Generated by Django 5.1.1 on 2024-09-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="name",
            new_name="title",
        ),
    ]
