# Generated by Django 5.1.1 on 2024-09-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(blank=True, to="social_media.profile"),
        ),
    ]
